#just putting this here so i can move stuff to a vm
import tkinter as tk
from tkinter import *


root = Tk()
root.title("Pandora's Box")
root.geometry("200x80")
root.configure(bg="#a44689")


def box():
        

        win1 = Tk()
        win1.title("Uh Oh")
        win1.geometry("150x100")
        word_label = Label(win1, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win1.mainloop()
        
        win2 = Tk()
        win2.title("Uh Oh")
        win2.geometry("150x100")
        word_label = Label(win2, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win2.mainloop()
        
        win3 = Tk()
        win3.title("Uh Oh")
        win3.geometry("150x100")
        word_label = Label(win3, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win3.mainloop()
        
        win4 = Tk()
        win4.title("Uh Oh")
        win4.geometry("150x100")
        word_label = Label(win4, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win4.mainloop()
        
        win5 = Tk()
        win5.title("Uh Oh")
        win5.geometry("150x100")
        word_label = Label(win5, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win5.mainloop()
        
        win6 = Tk()
        win6.title("Uh Oh")
        win6.geometry("150x100")
        word_label = Label(win6, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win6.mainloop()
        
        win7 = Tk()
        win7.title("Uh Oh")
        win7.geometry("150x100")
        word_label = Label(win7, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win7.mainloop()
        
        win8 = Tk()
        win8.title("Uh Oh")
        win8.geometry("150x100")
        word_label = Label(win8, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win8.mainloop()
        
        win9 = Tk()
        win9.title("Uh Oh")
        win9.geometry("150x100")
        word_label = Label(win9, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win9.mainloop()

        win10 = Tk()
        win10.title("Uh Oh")
        win10.geometry("150x100")
        word_label = Label(win10, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win10.mainloop()
        
        win11 = Tk()
        win11.title("Uh Oh")
        win11.geometry("150x100")
        word_label = Label(win11, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win11.mainloop()
        
        win12 = Tk()
        win12.title("Uh Oh")
        win12.geometry("150x100")
        word_label = Label(win12, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win12.mainloop()
        
        win13 = Tk()
        win13.title("Uh Oh")
        win13.geometry("150x100")
        word_label = Label(win13, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win13.mainloop()
        
        win14 = Tk()
        win14.title("Uh Oh")
        win14.geometry("150x100")
        word_label = Label(win14, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win14.mainloop()

        win15 = Tk()
        win15.title("Uh Oh")
        win15.geometry("150x100")
        word_label = Label(win15, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win15.mainloop()
        
        win16 = Tk()
        win16.title("Uh Oh")
        win16.geometry("150x100")
        word_label = Label(win16, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win16.mainloop()
        
        win17 = Tk()
        win17.title("Uh Oh")
        win17.geometry("150x100")
        word_label = Label(win17, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win17.mainloop()
        
        win18 = Tk()
        win18.title("Uh Oh")
        win18.geometry("150x100")
        word_label = Label(win18, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win18.mainloop()

        win19 = Tk()
        win19.title("Uh Oh")
        win19.geometry("150x100")
        word_label = Label(win19, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win19.mainloop()
        
        win20 = Tk()
        win20.title("Uh Oh")
        win20.geometry("150x100")
        word_label = Label(win20, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win20.mainloop()
        
                
        win21 = Tk()
        win21.title("Uh Oh")
        win21.geometry("150x100")
        word_label = Label(win21, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win21.mainloop()
        
        win22 = Tk()
        win22.title("Uh Oh")
        win22.geometry("150x100")
        word_label = Label(win22, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win22.mainloop()
        
        win23 = Tk()
        win23.title("Uh Oh")
        win23.geometry("150x100")
        word_label = Label(win23, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win23.mainloop()
        
        win24 = Tk()
        win24.title("Uh Oh")
        win24.geometry("150x100")
        word_label = Label(win24, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win24.mainloop()
        
        win25 = Tk()
        win25.title("Uh Oh")
        win25.geometry("150x100")
        word_label = Label(win25, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win25.mainloop()
        
        win26 = Tk()
        win26.title("Uh Oh")
        win26.geometry("150x100")
        word_label = Label(win26, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win26.mainloop()
        
        win27 = Tk()
        win27.title("Uh Oh")
        win27.geometry("150x100")
        word_label = Label(win27, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win27.mainloop()
        
        win28 = Tk()
        win28.title("Uh Oh")
        win28.geometry("150x100")
        word_label = Label(win28, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win28.mainloop()
        
        win29 = Tk()
        win29.title("Uh Oh")
        win29.geometry("150x100")
        word_label = Label(win29, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win29.mainloop()

        win30 = Tk()
        win30.title("Uh Oh")
        win30.geometry("150x100")
        word_label = Label(win30, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win30.mainloop()
        
        win31 = Tk()
        win31.title("Uh Oh")
        win31.geometry("150x100")
        word_label = Label(win31, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win31.mainloop()
        
        win32 = Tk()
        win32.title("Uh Oh")
        win32.geometry("150x100")
        word_label = Label(win32, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win32.mainloop()
        
        win33 = Tk()
        win33.title("Uh Oh")
        win33.geometry("150x100")
        word_label = Label(win33, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win33.mainloop()
        
        win34 = Tk()
        win34.title("Uh Oh")
        win34.geometry("150x100")
        word_label = Label(win34, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win34.mainloop()

        win35 = Tk()
        win35.title("Uh Oh")
        win35.geometry("150x100")
        word_label = Label(win35, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win35.mainloop()
        
        win36= Tk()
        win36.title("Uh Oh")
        win36.geometry("150x100")
        word_label = Label(win36, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win36.mainloop()
        
        win37 = Tk()
        win37.title("Uh Oh")
        win37.geometry("150x100")
        word_label = Label(win37, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win37.mainloop()
        
        win38 = Tk()
        win38.title("Uh Oh")
        win38.geometry("150x100")
        word_label = Label(win38, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win38.mainloop()

        win39 = Tk()
        win39.title("Uh Oh")
        win39.geometry("150x100")
        word_label = Label(win39, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win39.mainloop()
        
        win40 = Tk()
        win40.title("Uh Oh")
        win40.geometry("150x100")
        word_label = Label(win40, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win40.mainloop()
        
        
        win41 = Tk()
        win41.title("Uh Oh")
        win41.geometry("150x100")
        word_label = Label(win41, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win41.mainloop()
        
        win42 = Tk()
        win42.title("Uh Oh")
        win42.geometry("150x100")
        word_label = Label(win42, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win42.mainloop()
        
        win43 = Tk()
        win43.title("Uh Oh")
        win43.geometry("150x100")
        word_label = Label(win43, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win43.mainloop()
        
        win44 = Tk()
        win44.title("Uh Oh")
        win44.geometry("150x100")
        word_label = Label(win44, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win44.mainloop()
        
        win45 = Tk()
        win45.title("Uh Oh")
        win45.geometry("150x100")
        word_label = Label(win45, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win45.mainloop()
        
        win46 = Tk()
        win46.title("Uh Oh")
        win46.geometry("150x100")
        word_label = Label(win46, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win46.mainloop()
        
        win47 = Tk()
        win47.title("Uh Oh")
        win47.geometry("150x100")
        word_label = Label(win47, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win47.mainloop()
        
        win48 = Tk()
        win48.title("Uh Oh")
        win48.geometry("150x100")
        word_label = Label(win48, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win48.mainloop()
        
        win49 = Tk()
        win49.title("Uh Oh")
        win49.geometry("150x100")
        word_label = Label(win49, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win49.mainloop()

        win50 = Tk()
        win50.title("Uh Oh")
        win50.geometry("150x100")
        word_label = Label(win50, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win50.mainloop()
        
        win51 = Tk()
        win51.title("Uh Oh")
        win51.geometry("150x100")
        word_label = Label(win51, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win51.mainloop()
        
        win52 = Tk()
        win52.title("Uh Oh")
        win52.geometry("150x100")
        word_label = Label(win52, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win52.mainloop()
        
        win53 = Tk()
        win53.title("Uh Oh")
        win53.geometry("150x100")
        word_label = Label(win53, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win53.mainloop()
        
        win54 = Tk()
        win54.title("Uh Oh")
        win54.geometry("150x100")
        word_label = Label(win54, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win54.mainloop()

        win55 = Tk()
        win55.title("Uh Oh")
        win55.geometry("150x100")
        word_label = Label(win55, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win55.mainloop()
        
        win56 = Tk()
        win56.title("Uh Oh")
        win56.geometry("150x100")
        word_label = Label(win56, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win56.mainloop()
        
        win57 = Tk()
        win57.title("Uh Oh")
        win57.geometry("150x100")
        word_label = Label(win57, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win57.mainloop()
        
        win58 = Tk()
        win58.title("Uh Oh")
        win58.geometry("150x100")
        word_label = Label(win58, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win58.mainloop()

        win59 = Tk()
        win59.title("Uh Oh")
        win59.geometry("150x100")
        word_label = Label(win59, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win59.mainloop()
        
        win60 = Tk()
        win60.title("Uh Oh")
        win60.geometry("150x100")
        word_label = Label(win60, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win60.mainloop()
                
        win61 = Tk()
        win61.title("Uh Oh")
        win61.geometry("150x100")
        word_label = Label(win61, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win61.mainloop()
        
        win62 = Tk()
        win62.title("Uh Oh")
        win62.geometry("150x100")
        word_label = Label(win62, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win62.mainloop()
        
        win63 = Tk()
        win63.title("Uh Oh")
        win63.geometry("150x100")
        word_label = Label(win63, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win63.mainloop()
        
        win64 = Tk()
        win64.title("Uh Oh")
        win64.geometry("150x100")
        word_label = Label(win64, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win64.mainloop()
        
        win65 = Tk()
        win65.title("Uh Oh")
        win65.geometry("150x100")
        word_label = Label(win65, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win65.mainloop()
        
        win66 = Tk()
        win66.title("Uh Oh")
        win66.geometry("150x100")
        word_label = Label(win66, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win66.mainloop()
        
        win67 = Tk()
        win67.title("Uh Oh")
        win67.geometry("150x100")
        word_label = Label(win67, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win67.mainloop()
        
        win68 = Tk()
        win68.title("Uh Oh")
        win68.geometry("150x100")
        word_label = Label(win68, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win68.mainloop()
        
        win69 = Tk()
        win69.title("69")
        win69.geometry("150x100")
        word_label = Label(win69, font=("Comic Sans", 30, 'bold'))
        word_label.config(text="nice")
        word_label.pack(anchor="center", pady=30)
        win69.mainloop()

        win70 = Tk()
        win70.title("Uh Oh")
        win70.geometry("150x100")
        word_label = Label(win70, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win70.mainloop()
        
        win71 = Tk()
        win71.title("Uh Oh")
        win71.geometry("150x100")
        word_label = Label(win71, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win71.mainloop()
        
        win72 = Tk()
        win72.title("Uh Oh")
        win72.geometry("150x100")
        word_label = Label(win72, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win72.mainloop()
        
        win73 = Tk()
        win73.title("Uh Oh")
        win73.geometry("150x100")
        word_label = Label(win73, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win73.mainloop()
        
        win74 = Tk()
        win74.title("Uh Oh")
        win74.geometry("150x100")
        word_label = Label(win74, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win74.mainloop()

        win75 = Tk()
        win75.title("Uh Oh")
        win75.geometry("150x100")
        word_label = Label(win75, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win75.mainloop()
        
        win76 = Tk()
        win76.title("Uh Oh")
        win76.geometry("150x100")
        word_label = Label(win76, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win76.mainloop()
        
        win77 = Tk()
        win77.title("Uh Oh")
        win77.geometry("150x100")
        word_label = Label(win77, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win77.mainloop()
        
        win77 = Tk()
        win77.title("Uh Oh")
        win77.geometry("150x100")
        word_label = Label(win77, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win77.mainloop()

        win78 = Tk()
        win78.title("Uh Oh")
        win78.geometry("150x100")
        word_label = Label(win78, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win78.mainloop()
        
        win79 = Tk()
        win79.title("Uh Oh")
        win79.geometry("150x100")
        word_label = Label(win79, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win79.mainloop()
                
        win80 = Tk()
        win80.title("Uh Oh")
        win80.geometry("150x100")
        word_label = Label(win80, font=("Comic Sans", 30, 'bold'))
        word_label.config(text=":3")
        word_label.pack(anchor="center", pady=30)
        win80.mainloop()
box_button = tk.Button(root, text="Open the Box?", font=("Comic Sans", 13), command=box)
box_button.pack(pady=15)



root.mainloop()
